# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "v1-account"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "v1-account"
region = "eu-central-1"
parameter_overrides = "AppId=\"TradeJournal\" Stage=\"dev\" UserPoolArn=\"arn:aws:cognito-idp:eu-central-1:847495510557:userpool/eu-central-1_BWXrJCpu0\" TablePrefix=\"AccountTable\""
image_repositories = []
disable_rollback = true

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
